In [1]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, cv, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report
from sklearn.model_selection import learning_curve
from sklearn.linear_model import LogisticRegression
import ml_tools as ml
import help_tools as ht
import imp # imp.reload

import warnings
warnings.filterwarnings('ignore')

<u>Полезные ссылки</u>  
https://habr.com/ru/companies/ods/articles/328372/ - метрики в ml  
https://habr.com/ru/companies/ods/articles/322626/ - открытый курс ml Mail.ru  
https://education.yandex.ru/handbook/ml - онлайн учебник ml, yandex  
https://catboost.ai/en/docs/ - документация по catboost

#### Общие моменты

<u>Постановка задач классификации и регрессии</u>  
Имеем датасет из N объектов у которых есть x1,x2...xk признаков (они же фичи).  
У каждого объекта есть целевой признак Y (он же таргет)  

Задача ML:
сопоставление X -> Y_pred, предсказание таргета для каждого объекта по его фичам.  
Задача классификации: можество Y_pred дискретное (0, 1, ...); бинарная, когда Y_pred = (0, 1)  
Задача регрессии: Y_pred = множество действительных чисел (например предикт выручки для каждого объекта).  
  
Задача ML = задача оптимизации некоторой метрики = функции ошибок (функция потерь, <u>Loss-func</u>) считаемой  
на множестве (X, Y, Y_pred). Чем ближе Y_pred к реальной Y - тем меньше значения функции ошибок.  

Основной Loss-funс для бин. классификации = LogLoss = f(log(Y_pred), Y_pred, Y) = max функции правдоподобия  
Правдоподобие = вероятность наблюдать данные реализации случ. величин при некотором заданном распределении.
Для многоклассовой регрессии используется другая метрика - MultiClass.

Основной Loss-func для регрессии = RMSE (root_mean sq err) = sum(y^2-y_pred^2)/N  
Подробнее про него можно чекнуть в разделах AB&CI, на нем построен МНК метод.

Альтернативные функции потерь:  
MAE = sum(|y-y_pred|)/N - меньше штраф за сильные отклонения (нет квадрата) - для выборок большим размахом  
MAPE = sum(|y-y_pred/y|)/N - относительные отклонения, когда важен порядок, а не масштаб  
Для разных задач Loss_func(X, Y, Y_pred) могут отличаться - большой список возможных функций здесь:   https://catboost.ai/en/docs/references/training-parameters/common  
Можно писать свою функцию учитывая необходимость штрафов за ошибки разного рода.

<u>Переобучение и валидация</u>  
Если скормить модели данные X,Y -> то она может просто запомнить маппинг X->Y  (Y_pred = Y; Lossfunc = 0)  
Но для нового датасета X_new вырастет число ошибок = переобучение.  
  
Борьба с переобучением - подбор <u>гиперпараметров</u> модели, регулируя ее сложность относительно данных.
Пример: модель = полином N степени, чем выше N тем выше риск переобучения итд.  
Модель должна уловить общие закономерности данных, а не запомнить датасет.  
  
При подборе гиперпараметров - необходима валидация = оценка на тестовом датасете качества модели.  
Наиболее корректный способ кросс-валидация = делим выборку X на K частей (фолдов),  
далее делаем K иттераций в каждой из которых = модель учится на K-1 части, валидируется на оставшейся.  

Метрики качества обучения построены на принципе оценки ошибок первого и второго рода.  
Про возможные метрики см подробнее ниже в разделе "Метрики качества"

#### Линейные модели

https://education.yandex.ru/handbook/ml/article/linear-models  

Для общей задачи поиска func: func(X) = Y_pred можно использовать лин. функции  
func = w1 * x1 + w2 * x2 + ...  = задачи линейной регрессии и классификации.  
  
Допущение о данных:
1. существует гиперплоскость, которая их эффективно разделяет  
2. гомоскедастичность остатков (=дисперсия ошибок равномерная).  
Пример: датчик скорости авто ошибается одинаково для больших и малых скоростей  
Тогда разброс значений модели постоянен для разных диапазонов данных.
3. отсутствие сильных выбросов (т.к модель минимизирует среднее = не робастное)  
4. слабая попарная корреляция признаков (иначе = сингулярность и неустойчивость решения) - см ниже

<u>Линейная регрессия</u>  
Подробнее про регрессию можно чекнуть в AB&CI тетрадке, а также в Статистика.  
Некоторые важные особенности линейной регрессии:
1. Может отражать даже нелинейные зависимости вроде y = x1^2 + x2^3 ..., если  
сделать замену переменных x_new = x1^2 итд (полиномиальные регрессии или другого рода).  
2. Выдает веса w1,... обладающие интерпретируемостью. Но важно учитывать  
зависимость регрессии от масштаба данных (можно их нормализовывать итд - раздел Препроцессинг)
3. Решается аналитически (МНК), но обращение матрицы X - вычислительно сложная продцедура,  
поэтому применяют методы градиентного спуска = задаем веса W, считаем ошибки (Y-Y_pred), оцениваем градиент  
grad_W в сторону минимизации LossFunc, корректируем веса (шаг dW = learning rate) итд.  
Стохастичекий спуск = оцениваем градиент по случ. w_i (не по всем) -> больше шагов, но быстрее сходится.  
Кроме того, grad_W примерно можно оценивать не по всем данным X, а по случайной выборке.  
Т.е стохастичность и по колонкам и по кол-ву строк в X.
4. Ломается при det_X ~ 0 = коррелирующие  признаки X (т.к возникает множественность оптимальной прямой разбиения = сингулярность). Если признаки примерно коррелирующие, т е det_X ~ 0, это тоже проблема:
малое изменение признаков x -> большие изменения в предикте -> рост весов w (важность искуственно завышается)
5. Высокие отдельные веса w - высокое внимание модели к этим признакам -> сигнал к переобучению, т к 
небольшие изменения этих признаков приведут к сильному движению в прогнозах. При этом, при мультиколлинеарности высокие веса не будут отражать реальную важность признаков для предсказания. 
6. Для борьбы с проблемой высоких весов (aka переобучения здесь) - используют <u>регуляризацию</u>.  
Регуляризация = штраф модели за высокие значения отдельных весов: Loss_func_r = Loss_func + k * L    
k = коэф. регуляризации; L = L1, L2; L1 = |w1| + |w2| + ...; L2 = w1^2 + w2^2 + ...  
Матричная интерпретация: смещаем матрицу M=X^TX на k * I, чтобы det_M > 0. Решение менее точное,  
но без вычислительных проблем с сингулярностью. k - гиперпараметр, сила регуляризации  
PS. В основном хорошо работает L=L2, L1 не дифференциируется (сложнее искать grad), зато обнуляет  
неважные признаки (или коррелированные), что может быть полезно для прореживания весов (сокращение кол-ва).  
  
<u>Линейный классификатор</u>  
Идея в том, чтобы предсказывать y_pred = f(X) = (0, 1, ...)  
Loss_func = RMSE подходит плохо, так как плохо штрафует за близкие по X объекты с разными таргетами.  
У разделяющей поверхности сумма квадратов расстояний может быть большим, это ок.  
Основа функции потерь для классификатора M = margin = sign(y_pred * y) * (w * X) - <u>отступ</u>  
Это расстояние до плоскости разделения со знаком верности прогноза. abs(M) = уверенность классификатора.

Loss_func = f(M). Варианты классификаторов в зависимости от M:
1. Loss_func = sum(max(0, 1 - M)) = SVM (метод опорных векторов).  
Делаем плоскость равноудаленной от обоих разделяемых классов -> максимизируем сильную корректную уверенность.   
Был популярен в 60-х годах - мало параметров для настройки, точное мат. решение.
2. Loss_func = logit_func(M) = логистическая регрессия.  
Пусть модель дает нам вероятность того, что y = 1. Тогда можно максимизировать правдоподобие -  
шанс получить данные y(X). для объекта при условии вероятности для него p(X)  
Свяжем вероятность с отступом M для каждого объекта: M = logit(p) = log(p / 1-p)  
p/1-p = функция шансов; log - маппинг пространства 0;inf в пространство -inf;inf.  
Тогда p = sigmoida(M) -> loss_func = правдоподобие(p1, p2...) = правдоподобие(sigmoida(M)...)  
Логистическая <u>регрессия</u> потому что мы предсказываем не классы, а вещественные логиты.  
threshold - по которому вероятности proba сопоставляется класс 0;1 = гиперпараметр.  
  
<u>Множественная классификация</u>  
Пусть у нас есть множество классов, y_pred = 0, 1, 2, ... K  
Наиболее корректный вариант обучения - модель "все-против-всех"  
Обучаем K^2 классификаторов разделяющих классы i-j (все возможные пары).  
Получаем предикт по объекту X от всех пар - голосованием присваиваем таргет класса-победителя.

#### Метрические модели

Метод классификации или регрессии, при котором таргет тестовой точки выстраивается по ее <u>соседям</u> в  
признаковом пространстве из тренировочной выборки. (проще говоря: скажи мне кто твой друг).  
Фаза обучения отсутствует - тренировочная выборка запоминается, далее вычисления происходят для каждого  
тестового семпла (поиск соседей, оценка итогового таргета) = ленивая модель.  
  
Допущение о данных:  
1. смысловая близость объектов эквивалентна метрической (метрику расстояния можно вычислять)  
2. произвольные законы распределения данных, классов  
3. наличие большого кол-ва данных при большом кол-ве признаков X (проклятие размерности)  
Причина: чем выше размерность - тем сложнее в фикс. окрестности найти для семпла соседа  
  
Плюсы алгоритмов:
1. высокая обобщающая способность и точность (часто используют как бейзлайны)  
2. хорошая интерпретируемость  
  
Минусы:
1. при большом кол-ве данных вычислительно сложная процедура
2. не для всех данных можно подобрать метрику расстояния  

Основные типы расстояний (здесь a,b - признаки двух объектов выборки в пространстве X):  
1. Евклидово = (b^2-a^2) + ... 
2. Манхеттен = |b-a| + ... (менее чувствителен к выбросам, тк нет квадрата)
3. Косинус = (a,b)/|a||b| (не зависит от норм векторов.  
Хорошо напр. в текстах, где схожесть объекта не изменится,  
если один текст станет в два раза длиннее предыдущего  
  
Алгоритмы поиска соседей по расстояниям:
1. Прямой = считаем расстояния для всех пар (a,b), отбираем K самых близких = очень долго
Также можно воспользоваться бинарной сортировкой за logN по признакам и далее искать соседей в данном поле.
2. Примерный = находим достаточно близкие объекты пусть и не максимальные. Метод случайного дерева:  
в выборке берем случ. два семпла, разделяем их гиперплоскостью, выбираем случ. полуплоскость, в ней повторяем иттерацию. Останавливаем иттерации тогда, когда в полученных разбиенях пространства (кластерах) <K семплов.  
Точки в каждом таком кластере называем соседями.  
  
Оценка таргета семпла по его соседям:  
1. Самый частый таргет у соседей (прямой алгоритм, но без оценки расстояний)  
2. Средневзвешенный на расстояния до соседей таргет
3. Таргет взвешенный на функцию K(R/w), R = расстояние; w = ширина. K = ядро алгоритма (разные варианты)  
w - гиперпараметр, задающий сложность алгоритма (по аналогии со степенью полиномов)  
Чем больше w - тем меньше зависимость решения от расстояния -> алгоритм более простой  
Чем меньше w - расстояние важнее -> модель умнее запоминает выборку, но есть риск переобучения.  
  
По аналогии с классификацией - возможна ядерная регрессия - даем взвешенные на расстояния  
до соседей предикты непрерывного таргета для разных объектов.  
  
<u>LSH (Locality-sensitive hashing) алгоритмы</u>  
Идея: поиск хеш функции для каждого типа расстояния, таких что, чем меньше R(a,b), тем выше вероятность  
коллизии в пространстве хешей P(hash(a) = hash(b))  
Подбирая гиперпараметры для хеш функций, можно регулировать разницу в вероятностях коллизий в зависимости от R.  
  
<u>Алгоритмы на графах HNSW = Hierarchical navigable small world</u>  
Идея - записать все данные тренировочной выборки в граф, удовлетворящий условиям:
1. Между любыми двумя точками существует короткий путь
2. Средняя степень вершины мала
Пример: правило 5 рукопожатий - от любого человека, до другого - часто менее 5 рукопожатий  
  
Далее при поиске соседей для тестового объекта X:  
1. выбираем произвольный объект в графе
2. идем в сторону соседа, который ближе к тестовому объекту в пространстве
3. повторяем так K "рукопожатий" пока не дойдем до близких соседей

In [13]:
# В sklearn поддерживается алгоритм поиска k ближ соседей через регрессию и классификацию 
# вид алгоритма - брут-форс, дерево итд.  
from sklearn.neighbors import KNeighborsClassifier

# Пример данных X здесь двумерное пространство точек arr(obj1, obj2, ...); y = таргеты
X_train = [[1, 2], [2, 3], [3, 4], [5, 6]]
y_train = [0, 0, 1, 1]


knn = KNeighborsClassifier(n_neighbors=2, algorithm = 'auto', metric = 'manhattan')
# knn_regressor = KNeighborsRegressor(n_neighbors=3) # аналогично на вещественной выборке Y
knn.fit(X_train, y_train) # запомнили тренировочную выборку

# ленивые вычисления с поиском ближ соседей по расстоянию metric и методу algorithm
new_data = [[2, 2], [10, 5]]
prediction = knn.predict(new_data)
distances, indices = knn.kneighbors(new_data)
print('предсказываемые Y ', prediction)
print('расстояния до ближ соседей для каждой тестовой точки ', distances)
print('индексы ближ соседей в выборке X_train ', indices)

предсказываемые Y  [0 1]
расстояния до ближ соседей для каждой тестовой точки  [[1. 1.]
 [6. 8.]]
индексы ближ соседей в выборке X_train  [[0 1]
 [3 2]]

#### Градиентный бустинг TODO

https://habr.com/ru/companies/ods/articles/327250/

TODO  
теорема присяжных = стекинг слабых моделей  
в чем градиентность?  
стохатический бустинг = стохастика по признакам и кол-ву данных  
стекинг = объединение моделей в ансамбли
gbm - xgboost - catboost


<u>Градиентный бустинг в catboost</u>  
В catboost помимо loss-func можно задавать eval_metric = AUC, F1, ...  
Градиентный бустинг работает по иттеративному принципу:  
iter=1 строится дерево глубины depth - минимизирующее loss_func  
iter=2 поверх него строится доп дерево, минимизирующее ошибки первого дерева (ансамбль 2 деревьев)  
...  
iter=1000 ансамбль 1000 деревьев, последовательно минимизирующих ошибки предыдущих слоев.  
  
В итоге получаем N = iterations ансамблей разного кол-ва слоев.  
Чем больше N - тем меньше Log-loss, но не обязательно eval_metric  
Модель следит за динамикой eval_metric и может остановить обучение, если метрика не улучшается.  
use_best_model опция = выбрать самый лучший ансамбль из построенных по метрике eval.  
Ориентирование на eval_metric используя test_pool (см в CatboostClassifier) позволяет избежать переобуч.

#### CatBoostClassifier

In [2]:
# ПОДГОТОВКА ДАННЫХ

# классическая задача о выживших на титанике
df = pd.read_csv('./data/titanic.csv')
y = df.Survived.values

def prep_name(x):
    x = x.replace('Mlle', 'Miss').replace('Ms', 'Miss').replace('Mme', 'Mrs')
    if 'mr.' in x:
        return 'mr'
    if 'mrs.' in x:
        return 'mrs'
    if 'miss' in x:
        return 'miss'
    if 'master.' in x:
        return 'master'
    else:
        return 'name_null'
df['name_type'] = df.Name.apply(str.lower).apply(prep_name)

# рассматриваем как ординальное
# title_mapping = {"mr": 1, "miss": 2, "mrs": 3, "master": 4, "rare": 5}
# df['name_type'] = df['name_type'].map(title_mapping)
# df['name_type'] = df['name_type'].fillna(0)

#
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = 0
df.loc[df['FamilySize'] == 1, 'IsAlone'] = 1
df['Age*Class'] = df.Age * df.Pclass

df_x = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Fare', 'Embarked', 'name_type', 
           'Parch', 'FamilySize', 'IsAlone', 'Age*Class']]

# Вариант обработки категориальных фичей через OHE, но для catboost лучше - встроенные методы
# df_x = pd.get_dummies(df_x, columns=['Sex', 'Embarked'])

categorical_columns = ['name_type', 'Sex', 'Embarked']
# df_x = df_x[['name_type']]; categorical_columns = ['name_type'] # проверка на плохих данных

In [14]:
# БЕЙЗЛАЙН
X_train, X_test, y_train, y_test = train_test_split(df_x, y, test_size=0.33)

# инициализируем тренировочную и обучающую выборки
train_pool = ml.get_pool(X_train, y_train, categorical_columns)
test_pool = ml.get_pool(X_test, y_test, categorical_columns)

# инициализируем гиперпараметры модели
params = {
    'depth': 6, # глубина деревьев (больше = сложнее зависимости, но дольше и риск переобуч)
    'learning_rate': 0.03, # шаг изменения параметров при добавлении нового дерева в ансамбль (аналогично depth)
    'iterations': 1000, # количество деревьев в ансамбле
    'l2_leaf_reg': 3, # штраф за большие веса в листьях (аналогично рег. в регрессии)
    'bagging_temperature': 1, # интенсивность рандомизации при бустрапе в ансамбле
    'auto_class_weights': 'Balanced', # автоматически присвоить веса меткам обр. пропорционально частоте
    'random_strength': 1, # рандомизация сплитования (также влияет на переобучение)
    'loss_function' : 'Logloss', # функция потерь которую оптимизиуем при обучении дерева
    'eval_metric' : 'F1', # метрика, которую оптимизирует ансамбль
    'verbose' : False, # не выводить логи с каждой иттерации (можно указать частоту)
#     'silent' : False # полностью отключить вывод логов модели когда true 
}
   
# обучение модели на тестовых данных
model = CatBoostClassifier(**params)
model.fit(train_pool, eval_set=test_pool, use_best_model=True)

# оценка качества и важность фичей
print(ml.get_model_score(y_test, model.predict(test_pool), model.predict_proba(test_pool)[:, 1]))
pd.DataFrame({'feature' : test_pool.get_feature_names(), 
              'feature_importance' : model.feature_importances_}).sort_values(by='feature_importance',
                                                                             ascending=False).head(5)

{'precision': 0.808695652173913, 'recall': 0.8157894736842105, 'f1-score': 0.812227074235808, 'support': 114, 'accuracy': 0.8542372881355932, 'roc_auc': 0.894155277697005}

      feature  feature_importance
4        Fare           19.591006
6   name_type           16.839020
10  Age*Class           15.118700
5    Embarked           13.122874
2         Age           10.824380

In [260]:
# Кросс-валидация на k фолдах
# https://catboost.ai/en/docs/concepts/python-reference_cv
# fold_count = 3-10; чем выше - тем больше точность модели, но дольше обучение
fold_count = 5
pool = ml.get_pool(df_x, y, categorical_columns)
get_cv(params, pool, fold_count)

,iterations,test-F1-mean,test-F1-std,train-F1-mean,train-F1-std,test-Logloss-mean,test-Logloss-std,train-Logloss-mean,train-Logloss-std
999,999,0.789177,0.03826,0.966877,0.006496,0.48926,0.07747,0.139636,0.013181

In [133]:
# Learning curve - кривая зависимости качества обучения от кол-ва тренировочных данных
# https://habr.com/ru/companies/ods/articles/323890/
# По хорошему - надо отложить тестовый датасет и проверять предикт варьируя тренировочный
# Здесь примерно оцениваем качество через cv наращивая объем total-данных
# TODO - сделать нормально!
def calc_learning_curve(df_x, y, model_params, 
                        train_frac_list = np.linspace(0.5, 1.0, 5),
                        categorical_columns=None):
    """
    Более правильная методика: отложили df_test датасет
    Варьируем размер df_train -> смотрим как рас
    """
    df_stat = pd.DataFrame(None, columns=['data_frac', 'eval_mean', 'eval_std']); j=0
    for s in train_frac_list:
        if s < 1:
            X_train, _, y_train, _ = train_test_split(df_x, y, test_size=1-s)
        else:
            X_train, y_train = df_x, y
        
        sub_pool = ml.get_pool(X_train, y_train, categorical_columns)
        res = get_cv(model_params, sub_pool, fold_count=5)
        df_stat.loc[j, :] = s, res.iloc[0, 1], res.iloc[0, 2]; j+=1
    return df_stat

In [160]:
# Оптимизация гиперпараметров
# https://catboost.ai/en/docs/concepts/python-reference_catboost_randomized_search
param_grid = {
    'iterations': [1000, 5000, 10000],
    'learning_rate': [0.01, 0.03, 0.05],
    'eval_metric' : 'AUC:hints=skip_train~false'
}

model = CatBoostClassifier(**params)
pool = get_pool(df_x, y, categorical_columns)

# или model.randomized_search с параметром n_iter
grid_search_result = model.grid_search(param_grid,
                                       X=pool, # или X,y если не создан pool
                                       cv=3, # кросс-валидация на каждом шаге для оценки
                                       plot=False,
                                       verbose=0
                                      )

best_params = grid_search_result['params']

In [ ]:
# TODO
# StratifiedKFold - для кросс валидацией с проблемой классов

#### Метрики качества моделей

https://habr.com/ru/companies/ods/articles/328372/  
Обучаем модель на тренировочных данных, затем валидируем ее предсказания на df_test.  
Для классификаторов можно построить confusion matrix = матрица ошибок из четырех чисел:   
1. TN = true negative (predict=0, real=0; т е модель сказала Negative и это правда так)  
2. TP = true positive (predict=1, real=1)  
3. FP = false positive (predict=1, real=0)  
4. FN = false negative (predict=0, real=1)  

Собственно, из этих 4 чисел два числа FP, FN - это ошибки модели.  
1. FP - связано с ошибками первого рода (ложный прокрас)  
2. FN - связано с ошибками второго рода (ложный не-прокрас)  

Пусть N = TN+TP+FP+FN (все предсказания модели = размер тестового датасета)  
В задачах классификации используют следующие метрики качества модели:

1. Accuracy = (TN + TP) / N (точность; плохо работает с несбалансированными классами)
2. Precision = TP / (TP + FP) (точность2; какая доля положительный предсказаний корректна - прокси err-1type)
3. Recall = TP / (TP + FN) (полнота; какую долю реальных 1 алгоритм находит - прокси error-2type)
4. F1-score = 2 * Precision * Recall / (Precision + Recall) (ср гармоническое метрик для баланса)

Precision & Recall контролят ошибки 1 и 2 рода, не зависят от сбалансированности классов.  
Для оценки Accuracy необходимо посчитать средневзвешенное по классам значение

ROC-AUC = Receiver Operating Characteristic Area Under the Curve  
ROC-AUC оценивает способность модели различать классы на основе вероятностных предсказаний.  
Это метрика, которая анализирует поведение модели при различных порогах классификации  

----
Важно:
использовать ROC AUC рекомендуется при более сбалансированных классах, кроме того когда нет явного  
предпочтения по ошибкам первого и второго рода. Более того, оценка возможна на основе моделей,  
которые выдают вероятностные оценки для семплов.  
F1-score можно использовать когда надо сбалансировать точность и полноту предсказаний.

In [253]:
# упростим датасет для обучения
df = pd.read_csv('./data/titanic.csv')
y = df.Survived.values
df_x = df[['Sex', 'Age', 'Fare']]
df_x.Sex = df_x.Sex.replace('male', 1).replace('female', 0)

# обучим простую логистическую регрессию
X_train, X_test, y_train, y_test = train_test_split(df_x.fillna(999), y, test_size=0.33)

model = LogisticRegression(max_iter=200)
model.fit(X_train.values, y_train)
y_pred = model.predict(X_test.values) # предсказания классов
y_probability = model.predict_proba(X_test.values)[:, 1] # вероятность принадлежности к классу 1

# матрица ошибок
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
# посчитаем вручную некоторые ошибки
accuracy, precision, recall = (tn+tp) / (tn+fp+fn+tp), tp/(tp+fp), tp/(tp+fn)
print(f'расчетные значения accuracy = {accuracy}, precision = {precision}, recall = {recall}')

# посчитаем через sklearn функции:
ml.get_model_score(y_test, y_pred, y_probability)

расчетные значения accuracy = 0.7661016949152543, precision = 0.7009345794392523, recall = 0.6696428571428571

{'precision': 0.7009345794392523,
 'recall': 0.6696428571428571,
 'f1-score': 0.6849315068493149,
 'support': 112,
 'accuracy': 0.7661016949152543,
 'roc_auc': 0.7964480874316939}