In [166]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, cv, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report
from sklearn.model_selection import learning_curve
from sklearn.linear_model import LogisticRegression


import warnings
warnings.filterwarnings('ignore')

# полезные ссылки
# https://habr.com/ru/companies/ods/articles/323890/
# https://habr.com/ru/companies/ods/articles/328372/ - метрики в ml

In [252]:
import imp
imp.reload(ml_tools)
import ml_tools as ml

#### CatBoostClassifier

In [255]:
# ПОДГОТОВКА ДАННЫХ

# классическая задача о выживших на титанике
df = pd.read_csv('./data/titanic.csv')
y = df.Survived.values

def prep_name(x):
    x = x.replace('Mlle', 'Miss').replace('Ms', 'Miss').replace('Mme', 'Mrs')
    if 'mr.' in x:
        return 'mr'
    if 'mrs.' in x:
        return 'mrs'
    if 'miss' in x:
        return 'miss'
    if 'master.' in x:
        return 'master'
    else:
        return 'name_null'
df['name_type'] = df.Name.apply(str.lower).apply(prep_name)

# рассматриваем как ординальное
# title_mapping = {"mr": 1, "miss": 2, "mrs": 3, "master": 4, "rare": 5}
# df['name_type'] = df['name_type'].map(title_mapping)
# df['name_type'] = df['name_type'].fillna(0)

#
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = 0
df.loc[df['FamilySize'] == 1, 'IsAlone'] = 1
df['Age*Class'] = df.Age * df.Pclass

df_x = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Fare', 'Embarked', 'name_type', 
           'Parch', 'FamilySize', 'IsAlone', 'Age*Class']]

# Вариант обработки категориальных фичей через OHE, но для catboost лучше - встроенные методы
# df_x = pd.get_dummies(df_x, columns=['Sex', 'Embarked'])

categorical_columns = ['name_type', 'Sex', 'Embarked']
# df_x = df_x[['name_type']]; categorical_columns = ['name_type'] # проверка на плохих данных

In [259]:
# БЕЙЗЛАЙН
X_train, X_test, y_train, y_test = train_test_split(df_x, y, test_size=0.33)

# инициализируем тренировочную и обучающую выборки
train_pool = ml.get_pool(X_train, y_train, categorical_columns)
test_pool = ml.get_pool(X_test, y_test, categorical_columns)

# инициализируем гиперпараметры модели
params = {
    'depth': 6, # глубина деревьев (больше = сложнее зависимости, но дольше и риск переобуч)
    'learning_rate': 0.03, # шаг изменения параметров при добавлении нового дерева в ансамбль (аналогично depth)
    'iterations': 1000, # количество деревьев в ансамбле
    'l2_leaf_reg': 3, # штраф за большие веса в листьях (аналогично рег. в регрессии)
    'bagging_temperature': 1, # интенсивность рандомизации при бустрапе в ансамбле
    'auto_class_weights': 'Balanced', # автоматически присвоить веса меткам обр. пропорционально частоте
    'random_strength': 1, # рандомизация сплитования (также влияет на переобучение)
    'loss_function' : 'Logloss', # функция потерь которую оптимизиуем при обучении дерева
    'eval_metric' : 'F1', # метрика, которую оптимизирует ансамбль
    'verbose' : False, # не выводить логи с каждой иттерации (можно указать частоту)
#     'silent' : False # полностью отключить вывод логов модели когда true 
}
   
# обучение модели на тестовых данных
model = CatBoostClassifier(**params)
model.fit(train_pool, eval_set=test_pool, use_best_model=True)

# оценка качества и важность фичей
print(ml.get_model_score(y_test, model.predict(test_pool), model.predict_proba(test_pool)[:, 1]))
pd.DataFrame({'feature' : df_x.columns, 
              'feature_importance' : model.feature_importances_}).sort_values(by='feature_importance',
                                                                             ascending=False).head(5)

{'precision': 0.7017543859649122, 'recall': 0.8080808080808081, 'f1-score': 0.7511737089201878, 'support': 99, 'accuracy': 0.8203389830508474, 'roc_auc': 0.8478664192949907}

      feature  feature_importance
6   name_type           19.446686
1         Sex           13.905724
0      Pclass           12.746085
4        Fare           12.548484
10  Age*Class           11.226811

In [260]:
# Кросс-валидация на k фолдах
# https://catboost.ai/en/docs/concepts/python-reference_cv
# fold_count = 3-10; чем выше - тем больше точность модели, но дольше обучение
fold_count = 5
pool = ml.get_pool(df_x, y, categorical_columns)
get_cv(params, pool, fold_count)

,iterations,test-F1-mean,test-F1-std,train-F1-mean,train-F1-std,test-Logloss-mean,test-Logloss-std,train-Logloss-mean,train-Logloss-std
999,999,0.789177,0.03826,0.966877,0.006496,0.48926,0.07747,0.139636,0.013181

In [133]:
# Learning curve - кривая зависимости качества обучения от кол-ва тренировочных данных
# https://habr.com/ru/companies/ods/articles/323890/
# По хорошему - надо отложить тестовый датасет и проверять предикт варьируя тренировочный
# Здесь примерно оцениваем качество через cv наращивая объем total-данных
# TODO - сделать нормально!
def calc_learning_curve(df_x, y, model_params, 
                        train_frac_list = np.linspace(0.5, 1.0, 5),
                        categorical_columns=None):
    """
    Более правильная методика: отложили df_test датасет
    Варьируем размер df_train -> смотрим как рас
    """
    df_stat = pd.DataFrame(None, columns=['data_frac', 'eval_mean', 'eval_std']); j=0
    for s in train_frac_list:
        if s < 1:
            X_train, _, y_train, _ = train_test_split(df_x, y, test_size=1-s)
        else:
            X_train, y_train = df_x, y
        
        sub_pool = ml.get_pool(X_train, y_train, categorical_columns)
        res = get_cv(model_params, sub_pool, fold_count=5)
        df_stat.loc[j, :] = s, res.iloc[0, 1], res.iloc[0, 2]; j+=1
    return df_stat

In [160]:
# Оптимизация гиперпараметров
# https://catboost.ai/en/docs/concepts/python-reference_catboost_randomized_search
param_grid = {
    'iterations': [1000, 5000, 10000],
    'learning_rate': [0.01, 0.03, 0.05],
    'eval_metric' : 'AUC:hints=skip_train~false'
}

model = CatBoostClassifier(**params)
pool = get_pool(df_x, y, categorical_columns)

# или model.randomized_search с параметром n_iter
grid_search_result = model.grid_search(param_grid,
                                       X=pool, # или X,y если не создан pool
                                       cv=3, # кросс-валидация на каждом шаге для оценки
                                       plot=False,
                                       verbose=0
                                      )

best_params = grid_search_result['params']

In [ ]:
# TODO
# StratifiedKFold - для кросс валидацией с проблемой классов

#### Метрики качества моделей

https://habr.com/ru/companies/ods/articles/328372/  
Обучаем модель на тренировочных данных, затем валидируем ее предсказания на df_test.  
Для классификаторов можно построить confusion matrix = матрица ошибок из четырех чисел:   
1. TN = true negative (predict=0, real=0; т е модель сказала Negative и это правда так)  
2. TP = true positive (predict=1, real=1)  
3. FP = false positive (predict=1, real=0)  
4. FN = false negative (predict=0, real=1)  

Собственно, из этих 4 чисел два числа FP, FN - это ошибки модели.  
1. FP - связано с ошибками первого рода (ложный прокрас)  
2. FN - связано с ошибками второго рода (ложный не-прокрас)  

Пусть N = TN+TP+FP+FN (все предсказания модели = размер тестового датасета)  
В задачах классификации используют следующие метрики качества модели:

1. Accuracy = (TN + TP) / N (точность; плохо работает с несбалансированными классами)
2. Precision = TP / (TP + FP) (точность2; какая доля положительный предсказаний корректна - прокси err-1type)
3. Recall = TP / (TP + FN) (полнота; какую долю реальных 1 алгоритм находит - прокси error-2type)
4. F1-score = 2 * Precision * Recall / (Precision + Recall) (ср гармоническое метрик для баланса)

Precision & Recall контролят ошибки 1 и 2 рода, не зависят от сбалансированности классов.  
Для оценки Accuracy необходимо посчитать средневзвешенное по классам значение

ROC-AUC = Receiver Operating Characteristic Area Under the Curve  
ROC-AUC оценивает способность модели различать классы на основе вероятностных предсказаний.  
Это метрика, которая анализирует поведение модели при различных порогах классификации  

----
Важно:
использовать ROC AUC рекомендуется при более сбалансированных классах, кроме того когда нет явного  
предпочтения по ошибкам первого и второго рода. Более того, оценка возможна на основе моделей,  
которые выдают вероятностные оценки для семплов.  
F1-score можно использовать когда надо сбалансировать точность и полноту предсказаний.

In [253]:
# упростим датасет для обучения
df = pd.read_csv('./data/titanic.csv')
y = df.Survived.values
df_x = df[['Sex', 'Age', 'Fare']]
df_x.Sex = df_x.Sex.replace('male', 1).replace('female', 0)

# обучим простую логистическую регрессию
X_train, X_test, y_train, y_test = train_test_split(df_x.fillna(999), y, test_size=0.33)

model = LogisticRegression(max_iter=200)
model.fit(X_train.values, y_train)
y_pred = model.predict(X_test.values) # предсказания классов
y_probability = model.predict_proba(X_test.values)[:, 1] # вероятность принадлежности к классу 1

# матрица ошибок
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
# посчитаем вручную некоторые ошибки
accuracy, precision, recall = (tn+tp) / (tn+fp+fn+tp), tp/(tp+fp), tp/(tp+fn)
print(f'расчетные значения accuracy = {accuracy}, precision = {precision}, recall = {recall}')

# посчитаем через sklearn функции:
ml.get_model_score(y_test, y_pred, y_probability)

расчетные значения accuracy = 0.7661016949152543, precision = 0.7009345794392523, recall = 0.6696428571428571

{'precision': 0.7009345794392523,
 'recall': 0.6696428571428571,
 'f1-score': 0.6849315068493149,
 'support': 112,
 'accuracy': 0.7661016949152543,
 'roc_auc': 0.7964480874316939}